
services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-latest}
    container_name: jirasm_postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - jirasm_postgres_data:/var/lib/postgresql/data
    networks:
      - jirasm_network

  jira:
    image: atlassian/jira-service-management:${JIRASM_VERSION:-latest}
    container_name: jirasm
    restart: unless-stopped
    ports:
      - "${HOST_PORT}:8080"
    environment:
      ATL_JDBC_URL: jdbc:postgresql://postgres:5432/jiradb
      ATL_JDBC_USER: ${POSTGRES_USER}
      ATL_JDBC_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    volumes:
      - jirasm_data:/var/atlassian/application-data/jira
    networks:
      - jirasm_network

volumes:
  jirasm_postgres_data:
  jirasm_data:

networks:
  jirasm_network:
    driver: bridge
